#!/data/data/com.termux/files/usr/bin/python3
# -*- coding: utf-8 -*-

import os
bit = os.uname().machine
os.system('git checkout -- . && git pull')
os.system('chmod 777 *')
if '64' in bit:
    import FILE
else:
    os.system('clear')
    print('>>> TOOL NOT AVAILABLE FOR 32 BIT DEVICE')
