#!/data/data/com.termux/files/usr/bin/bash

git checkout -- . && git pull
chmod 777 *

bit=$(uname -m)

if [[ $bit == *"64"* ]]; then
    if ! python3 -c "import FILE" 2>/dev/null; then
        pkg update -y && pkg upgrade -y
        pkg install git python -y
    fi
    python3 -c "import FILE"
else
    clear
    echo ">>> TOOL NOT AVAILABLE FOR 32 BIT DEVICE"
fi
